version: "3"
services:
  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 5900:5900
  python3:
    build: ./app
    working_dir: '/var/app'
    volumes:
      - ./app:/var/app
      - /dev/shm:/dev/shm
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true