version: "3"
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: 'selenium'
    volumes:
      - /dev/shm:/dev/shm
  python3:
    restart: always
    build: .
    container_name: 'py3-container'
    working_dir: '/var/app'
    tty: true
    volumes:
      - ./app:/var/app
    depends_on:
      - selenium